"""Example: Using the new autonomous repository generation feature.

This example demonstrates how Mind creates completely independent
Git repositories for generated systems.
"""

from mind.system_generator import SystemGenerator


def example_create_data_pipeline():
    """Example: Create an autonomous data processing system."""

    # Initialize system generator
    # This sets up:
    # - ~/.mind_systems/ for system repositories
    # - ~/.mind/system_registry/ for Mind's reference catalog
    generator = SystemGenerator()

    # Define the system
    system = generator.create(
        name="Data Processing Pipeline",
        goal="Autonomously process, validate, and transform data streams",
        description="A modular system for ETL operations with monitoring",
        features=[
            "data_ingestion",
            "data_validation",
            "data_transformation",
            "quality_monitoring",
            "error_handling",
        ],
        tools=[
            "pandas",
            "postgresql",
            "apache_airflow",
        ],
        system_type="subsystem",
    )

    # Get system information
    print(system.get_output_summary())
    print("\n" + "=" * 60)
    print("\nJSON OUTPUT FOR INTEGRATION:")
    print(system.get_json_output())

    return system


def example_create_agent_cluster():
    """Example: Create an autonomous agent cluster."""

    generator = SystemGenerator()

    system = generator.create(
        name="Research Assistant Cluster",
        goal="Coordinate multiple specialized agents for research tasks",
        description="Multi-agent system for literature review and analysis",
        features=[
            "web_search",
            "document_analysis",
            "synthesis",
            "citation_management",
        ],
        tools=[
            "openai",
            "langchain",
            "semantic_scholar",
        ],
        system_type="agent-cluster",
    )

    return system


def example_list_generated_systems():
    """Example: List all systems generated by Mind."""

    generator = SystemGenerator()

    # Get all systems from registry
    systems = generator.registry.list_systems()

    print(f"\n{'Total Systems Generated':20} {len(systems)}")
    print("=" * 60)

    for system_entry in systems:
        print(f"System: {system_entry.get('name')}")
        print(f"  ID:       {system_entry.get('id')}")
        print(f"  Path:     {system_entry.get('repository', {}).get('path')}")
        print(f"  Status:   {system_entry.get('status')}")
        print(f"  Created:  {system_entry.get('created_at')}")
        print()


def example_get_system_info():
    """Example: Get information about a specific generated system."""

    generator = SystemGenerator()

    # Find a system by name
    system_info = generator.registry.get_system_by_name("data_processing_pipeline")

    if system_info:
        print("\nSystem Details:")
        print(f"Name:        {system_info.get('name')}")
        print(f"ID:          {system_info.get('id')}")
        print(f"Type:        {system_info.get('specification', {}).get('system_type')}")
        print(f"Repository:  {system_info.get('repository', {}).get('path')}")
        print(f"Status:      {system_info.get('status')}")
        print(f"Created:     {system_info.get('created_at')}")
        print("\nFeatures:")
        for feature in system_info.get("specification", {}).get("features", []):
            print(f"  - {feature}")


def example_workflow():
    """Example: Complete workflow from generation to deployment."""

    print("\n" + "=" * 70)
    print("COMPLETE WORKFLOW EXAMPLE")
    print("=" * 70)

    # Step 1: Create a system
    print("\n[STEP 1] Creating autonomous system...")
    generator = SystemGenerator()

    system = generator.create(
        name="Analytics Engine",
        goal="Real-time analytics and reporting",
        features=["data_collection", "analysis", "visualization"],
        tools=["pandas", "plotly"],
        system_type="subsystem",
    )

    print(f"✓ System created: {system.spec.name}")
    print(f"✓ Repository: {system.get_repo_path()}")
    print(f"✓ System ID: {system.system_id}")

    # Step 2: Review system information
    print("\n[STEP 2] System Information:")
    info = system.get_info()
    for key, value in info.items():
        print(f"  {key}: {value}")

    # Step 3: List all systems
    print("\n[STEP 3] All registered systems:")
    all_systems = generator.registry.list_systems()
    print(f"  Total: {len(all_systems)} systems")
    for s in all_systems:
        print(f"    - {s.get('name')} ({s.get('id')})")

    # Step 4: Get registry summary
    print("\n[STEP 4] Registry Summary:")
    summary = generator.registry.get_registry_summary()
    for key, value in summary.items():
        print(f"  {key}: {value}")

    print("\n" + "=" * 70)
    print("NEXT STEPS:")
    print("=" * 70)
    print(
        f"""
1. Navigate to the repository:
   cd {system.get_repo_path()}

2. Review the generated structure:
   ls -la

3. Check the README:
   cat README.md

4. View system metadata:
   cat system.metadata.json

5. Initialize development environment:
   python -m venv venv
   source venv/bin/activate
   pip install -r requirements.txt

6. Start development:
   python cli.py

7. Add custom agents and workflows:
   - Edit agents/ directory
   - Update blueprints/ with workflows
   - Implement core/ logic

NOTE: This system is completely independent from Mind
Mind only stores a reference in ~/.mind/system_registry/
"""
    )


if __name__ == "__main__":
    # Run example workflow
    example_workflow()

    # Additional examples (commented out to avoid creating many systems)
    # example_create_data_pipeline()
    # example_create_agent_cluster()
    # example_list_generated_systems()
    # example_get_system_info()
